### ISSUE TITLE
Версия на JavaScript

### ISSUE THREAD

**Issue by slavafomin** [Olegf13/check_yandex_purse#2]
Круто вы заморочились, респект! :+1: 

Если будет желание, то было бы здорово сделать порт на JavaScript, чтобы можно было использовать на клиентской стороне и в коде на Node.js.

Если вдруг сделаете, то буду рад включить модуль в коллекцию универсальных валидаторов, которую мы планируем разработать для JS.

К сожалению сам портировать не могу из-за нехватки времени сейчас.

**Comment by Olegf13** [comment]
Спасибо! Порт на JS делать не стану, т.к. самому без надобности. 
Но если всё-таки решите сделать, дайте знать )
